version: '3.7'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_USER: test
        PMA_PASSWORD: test
        PMA_ARBITRARY: 1
    depends_on:
      - db
    volumes:
        - pma_data:/sessions

volumes:
    db_data:
    pma_data:
